# Generated by Django 5.0.7 on 2024-08-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0002_product_is_active_product_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
