# Generated by Django 5.0.7 on 2024-08-07 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0003_product_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="productcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="عنوان")),
                (
                    "url_title",
                    models.CharField(max_length=300, verbose_name="عنوان در url"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product_module.productcategory",
            ),
        ),
    ]
