# Generated by Django 5.0.7 on 2024-08-07 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0005_productinformation_product_information"),
    ]

    operations = [
        migrations.CreateModel(
            name="producttags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="عنوان تگ")),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="information",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product_module.productinformation",
            ),
        ),
    ]
