# Generated by Django 5.0.7 on 2024-08-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0006_producttags_alter_product_information"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producttags",
            old_name="title",
            new_name="tag",
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(to="product_module.producttags"),
        ),
    ]
