# Generated by Django 5.0.7 on 2024-08-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="contactus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=300, verbose_name="نام کاربری"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                ("subject", models.CharField(max_length=200, verbose_name=" موضوع")),
                ("comment", models.CharField(max_length=300, verbose_name="متن نظر")),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, max_length=300, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "response",
                    models.TextField(
                        blank=True, max_length=300, null=True, verbose_name="پاسخ ادمین"
                    ),
                ),
                (
                    "is_read_by_admin",
                    models.BooleanField(verbose_name="خوانده شده توسط ادمین"),
                ),
            ],
            options={
                "verbose_name": "تماس با ما",
                "verbose_name_plural": "لیست تماس با ما",
            },
        ),
    ]
